version: '3.9'
services:
  metabase:
    image: metabase/metabase-enterprise:v1.43.1
    container_name: metabase
    hostname: metabase
    volumes: 
    - /dev/urandom:/dev/random:ro
    - $PWD/logging_config:/metabase.db
    ports:
      - 3000:3000
      # if you want to go deep into JMX, uncomment the next line
      - 1099:1099
    environment: # using postgres app db and a max pool size of 2, add the JMX
      - "MB_DB_CONNECTION_URI=postgres://postgres-app-db:5432/metabase?user=metabase%40postgres-app-db&password=mysecretpassword"
      - "MB_JDBC_DATA_WAREHOUSE_MAX_CONNECTION_POOL_SIZE=2"
      - "MB_SEND_EMAIL_ON_FIRST_LOGIN_FROM_NEW_DEVICE=false"
      - "MB_SEND_NEW_SSO_USER_ADMIN_EMAIL=false"
      # uncomment the next line if you want to enable custom logging and/or JMX
      # - "JAVA_OPTS=-Dlog4j.configurationFile=file:///metabase.db/log4j2.xml -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.rmi.port=1099 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=metabase"
    # if you want to do some resource constrain, it's here
    # cpus: 1
    # mem_limit: 2048m
    networks: 
      - metanet1
    depends_on: 
      - postgres-app-db
  postgres-app-db:
    image: postgres:14.2-alpine
    container_name: postgres-app-db
    hostname: postgres-app-db
    environment:
      - "POSTGRES_USER=metabase@postgres-app-db"
      - "POSTGRES_DB=metabase"
      - "POSTGRES_PASSWORD=mysecretpassword"
    networks: 
      - metanet1
    cpus: 1
    mem_limit: 128m
  setup:
    image: bash:5.1.16
    container_name: setup
    volumes:
      - $PWD/setup:/tmp
    networks:
      - metanet1
    depends_on:
      - metabase
    command: sh /tmp/metabase-setup.sh metabase:3000
    cpus: 1
    mem_limit: 32mb
  mariadb-data:
    build: .
    container_name: mariadb-data
    hostname: mariadb-data
    ports:
      - 3306:3306
    networks: 
      - metanet1
    # cpus: 1
    # mem_limit: 64mb
networks: 
  metanet1:
    driver: bridge
